### ISSUE TITLE
[Bug] Encountered an exception whilst reading fusion metadata for pack 'builtin/aether_colorblind'

### ISSUE THREAD

**Issue by Maypul** [SuperMartijn642/Fusion#37]
**Version Info**
- Minecraft, 1.19.2
- Fusion, 1.1.0b

**Are you using OptiFine:**
No

**Description of the Bug**
Looks like Fusion can't real correctly metadata for Aether's built-in resource pack

**Steps to Reproduce**
Install Aether mod, install Fusion
Run game
Check the logs:

[20:49:36] [Render thread/ERROR] [fusion/]: Encountered an exception whilst reading fusion metadata for pack 'builtin/aether_colorblind':
java.io.FileNotFoundException: Can't find resource pack.mcmeta at packs/colorblind
at net.minecraftforge.resource.PathPackResources.m_5541_(PathPackResources.java:112) ~[forge-1.19.2-43.2.21-universal.jar%23632!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.server.packs.AbstractPackResources.m_5550_(AbstractPackResources.java:60) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.packs.repository.Pack.handler$bfh000$init(Pack.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
at net.minecraft.server.packs.repository.Pack.(Pack.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
at net.minecraft.server.packs.repository.Pack.(Pack.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
at net.minecraft.client.Minecraft.createClientPackAdapter(Minecraft.java:2771) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
at com.aetherteam.aether.Aether.lambda$setupColorblindPack$22(Aether.java:308) ~[aether-1.19.2-1.0.0-beta.2-forge.jar%23396!/:1.19.2-1.0.0-beta.2-forge] {re:classloading}
at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:47) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
at net.minecraft.client.Minecraft.(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23150!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66) [ForgeWrapper-1.5.7-prism.jar:1.5.7-prism] {}
at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?] {}
at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?] {}
at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}
[20:49:36] [Render thread/ERROR] [fusion/]: Encountered an exception whilst reading fusion metadata for pack 'builtin/aether_colorblind':
java.io.FileNotFoundException: Can't find resource pack.mcmeta at packs/colorblind
at net.minecraftforge.resource.PathPackResources.m_5541_(PathPackResources.java:112) ~[forge-1.19.2-43.2.21-universal.jar%23632!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.server.packs.AbstractPackResources.m_5550_(AbstractPackResources.java:60) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.packs.repository.Pack.handler$bfh000$init(Pack.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
at net.minecraft.server.packs.repository.Pack.(Pack.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
at net.minecraft.server.packs.repository.Pack.(Pack.java:79) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
at fuzs.resourcepackoverrides.client.packs.repository.ForwardingPack.(ForwardingPack.java:13) ~[ResourcePackOverrides-v4.0.4-1.19.2-Forge.jar%23588!/:4.0.4] {re:mixin,re:classloading}
at fuzs.resourcepackoverrides.client.packs.repository.ForwardingPack.copy(ForwardingPack.java:18) ~[ResourcePackOverrides-v4.0.4-1.19.2-Forge.jar%23588!/:4.0.4] {re:mixin,re:classloading}
at net.minecraft.server.packs.repository.PackRepository.mda7bccf$lambda$discoverAvailable$0$0(PackRepository.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$6(CollectCollectors.java:184) ~[guava-31.0.1-jre.jar%23116!/:?] {}
at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?] {}
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
at net.minecraft.server.packs.repository.PackRepository.handler$zjc000$discoverAvailable(PackRepository.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:52) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
at net.minecraft.client.Minecraft.(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23150!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66) [ForgeWrapper-1.5.7-prism.jar:1.5.7-prism] {}
at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?] {}
at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?] {}
at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}

Also reported on Aether: https://github.com/The-Aether-Team/The-Aether/issues/1880

**Comment by Krimatoria** [comment]
1.19.2
fusion-1.1.0c-forge-mc1.19.2.jar

> [18Feb2024 23:52:22.330] [Render thread/ERROR] [fusion/]: Encountered an exception whilst reading fusion metadata for pack 'builtin/aether_colorblind':
java.io.FileNotFoundException: Can't find resource pack.mcmeta at packs/colorblind
	at net.minecraftforge.resource.PathPackResources.m_5541_(PathPackResources.java:112) ~[forge-1.19.2-43.3.5-universal.jar%23730!/:?]
	at net.minecraft.server.packs.AbstractPackResources.m_5550_(AbstractPackResources.java:60) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.server.packs.repository.Pack.handler$cll000$init(Pack.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.client.Minecraft.createClientPackAdapter(Minecraft.java:2771) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at com.aetherteam.aether.Aether.lambda$setupColorblindPack$24(Aether.java:297) ~[aether-1.19.2-1.2.0-forge.jar%23429!/:1.19.2-1.2.0-forge]
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:47) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23122!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-mmc4.jar:mmc4]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18Feb2024 23:52:22.341] [Render thread/ERROR] [fusion/]: Encountered an exception whilst reading fusion metadata for pack 'builtin/aether_colorblind':
java.io.FileNotFoundException: Can't find resource pack.mcmeta at packs/colorblind
	at net.minecraftforge.resource.PathPackResources.m_5541_(PathPackResources.java:112) ~[forge-1.19.2-43.3.5-universal.jar%23730!/:?]
	at net.minecraft.server.packs.AbstractPackResources.m_5550_(AbstractPackResources.java:60) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.server.packs.repository.Pack.handler$cll000$init(Pack.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:79) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at fuzs.resourcepackoverrides.client.packs.repository.ForwardingPack.<init>(ForwardingPack.java:13) ~[ResourcePackOverrides-v4.0.4-1.19.2-Forge.jar%23651!/:4.0.4]
	at fuzs.resourcepackoverrides.client.packs.repository.ForwardingPack.copy(ForwardingPack.java:18) ~[ResourcePackOverrides-v4.0.4-1.19.2-Forge.jar%23651!/:4.0.4]
	at net.minecraft.server.packs.repository.PackRepository.mdb45b24$lambda$discoverAvailable$0$0(PackRepository.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$6(CollectCollectors.java:184) ~[guava-31.0.1-jre.jar%2388!/:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at net.minecraft.server.packs.repository.PackRepository.handler$zho000$discoverAvailable(PackRepository.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:52) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23725!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23122!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-mmc4.jar:mmc4]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by SuperMartijn642** [comment]
Besides the log spam, this shouldn't really affect anything.

It seems 1.19.3 and above handle a missing `pack.mcmeta` file the same as if the file was just missing the requested section, while 1.19.2 and below throw an error if the file is missing, hence why I likely missed it.
In Fusion version 1.1.1, the error will now simply be ignored and no longer printed to the logs.
Thank you for reporting the issue!
