### ISSUE TITLE
[Crash] Random crash on 1.20.1

### ISSUE THREAD

**Issue by SakuraKoi** [SuperMartijn642/Fusion#72]
**Version Info**
- Minecraft, 1.20.1
- Fusion, 1.1.1

**Are you using OptiFine:** No

**Steps to Reproduce**
sorry, idk how to reproduce
randomly crash, about 2-3 times in 6 hours

**Crash report**
```
Description: Encountered exception while building chunk meshes

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.shouldConnect(SurroundingBlockData.java:83) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.getConnections(SurroundingBlockData.java:74) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.create(SurroundingBlockData.java:42) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:165) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:170) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:123) ~[embeddium-0.3.14+mc1.20.1.jar%23368!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:50) ~[embeddium-0.3.14+mc1.20.1.jar%23368!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[embeddium-0.3.14+mc1.20.1.jar%23368!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207) ~[embeddium-0.3.14+mc1.20.1.jar%23368!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Embeddium (embeddium), Version: 0.3.14+mc1.20.1
		at TRANSFORMER/embeddium@0.3.14+mc1.20.1/me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:123)

	Fusion (fusion), Version: 1.1.1
		Issue tracker URL: https://github.com/SuperMartijn642/Rechiseled/issues
		at TRANSFORMER/fusion@1.1.1/com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.shouldConnect(SurroundingBlockData.java:83)
Stacktrace:
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.shouldConnect(SurroundingBlockData.java:83) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.getConnections(SurroundingBlockData.java:74) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.create(SurroundingBlockData.java:42) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:165) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:170) ~[fusion-1.1.1-forge-mc1.20.1.jar%23391!/:?] {re:classloading}
-- Block being rendered --
Details:
	Block: Block{rechiseled:diorite_diagonal_bricks_connecting}
	Block location: World: (-72,57,-20), Section: (at 8,9,12 in -5,3,-2; chunk contains blocks -80,-64,-32 to -65,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Chunk section: RenderSection at chunk (-5, 3, -2) from (-80, 48, -32) to (-65, 63, -17)
	Render context volume: BoundingBox{minX=-82, minY=46, minZ=-34, maxX=-63, maxY=65, maxZ=-15}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:123) ~[embeddium-0.3.14+mc1.20.1.jar%23368!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:50) ~[embeddium-0.3.14+mc1.20.1.jar%23368!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[embeddium-0.3.14+mc1.20.1.jar%23368!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207) ~[embeddium-0.3.14+mc1.20.1.jar%23368!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```
```
Description: Encountered exception while building chunk meshes

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.shouldConnect(SurroundingBlockData.java:83) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.getConnections(SurroundingBlockData.java:74) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.create(SurroundingBlockData.java:42) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:165) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:170) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:123) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:50) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Embeddium (embeddium), Version: 0.3.14+mc1.20.1
		at TRANSFORMER/embeddium@0.3.14+mc1.20.1/me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:123)

	Fusion (fusion), Version: 1.1.1
		Issue tracker URL: https://github.com/SuperMartijn642/Rechiseled/issues
		at TRANSFORMER/fusion@1.1.1/com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.shouldConnect(SurroundingBlockData.java:83)
Stacktrace:
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.shouldConnect(SurroundingBlockData.java:83) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.getConnections(SurroundingBlockData.java:74) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.create(SurroundingBlockData.java:42) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:165) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:170) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
-- Block being rendered --
Details:
	Block: Block{minecraft:bookshelf}
	Block location: World: (-58,64,1), Section: (at 6,0,1 in -4,4,0; chunk contains blocks -64,-64,0 to -49,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Chunk section: RenderSection at chunk (-4, 4, 0) from (-64, 64, 0) to (-49, 79, 15)
	Render context volume: BoundingBox{minX=-66, minY=62, minZ=-2, maxX=-47, maxY=81, maxZ=17}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:123) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:50) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```
```
Description: Encountered exception while building chunk meshes

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.shouldConnect(SurroundingBlockData.java:83) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.getConnections(SurroundingBlockData.java:74) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.create(SurroundingBlockData.java:42) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:165) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:170) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:123) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:50) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Embeddium (embeddium), Version: 0.3.14+mc1.20.1
		at TRANSFORMER/embeddium@0.3.14+mc1.20.1/me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:123)

	Fusion (fusion), Version: 1.1.1
		Issue tracker URL: https://github.com/SuperMartijn642/Rechiseled/issues
		at TRANSFORMER/fusion@1.1.1/com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.shouldConnect(SurroundingBlockData.java:83)
Stacktrace:
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.shouldConnect(SurroundingBlockData.java:83) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.getConnections(SurroundingBlockData.java:74) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.SurroundingBlockData.create(SurroundingBlockData.java:42) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:165) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
	at com.supermartijn642.fusion.model.types.connecting.ConnectingBakedModel.getModelData(ConnectingBakedModel.java:170) ~[fusion-1.1.1-forge-mc1.20.1.jar%23393!/:?] {re:classloading}
-- Block being rendered --
Details:
	Block: Block{minecraft:glass}
	Block location: World: (-51,66,16), Section: (at 13,2,0 in -4,4,1; chunk contains blocks -64,-64,16 to -49,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Chunk section: RenderSection at chunk (-4, 4, 1) from (-64, 64, 16) to (-49, 79, 31)
	Render context volume: BoundingBox{minX=-66, minY=62, minZ=14, maxX=-47, maxY=81, maxZ=33}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:123) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:50) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:APP:mixins.oculus.compat.sodium.json:shader_overrides.MixinChunkBuilderMeshingTask,pl:mixin:APP:flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207) ~[embeddium-0.3.14+mc1.20.1.jar%23370!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```

**Comment by SuperMartijn642** [comment]
The relevant code no longer exists as it has been mostly rewritten in Fusion 1.2.0, hence the crash should no longer occur.
Thank you for reporting the issue!
